// @ts-check
// Autogenerated from ../boards (the per-board hardware / bring-up notes).
/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  boards: [{type: 'autogenerated', dirName: '.'}],
};

export default sidebars;
