// @ts-check
// Autogenerated from ../docs so new .md files appear without editing config.
/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  docs: [{type: 'autogenerated', dirName: '.'}],
};

export default sidebars;
